import 'package:flutter/material.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../models/itinerary.dart';
import '../../widgets/planner/activity_card.dart';
import '../../widgets/planner/transit_connector.dart';
import '../../widgets/planner/ai_chat_input.dart';
import '../../widgets/planner/activity_detail_sheet.dart';
import '../../services/api_client.dart';
import '../../core/config/backend_config.dart';
import '../../services/backend/auth_service.dart';
import '../main/main_screen.dart';

/// Screen 10: AI-Generated Itinerary Detail Page
///
/// 规范来自 FLUTTER_UI_REDESIGN_INSTRUCTIONS.md Step UI-5.2
/// - Day Tab Bar (swipeable)
/// - Activity Cards with Navigate/Details buttons
/// - Transit Connectors between activities
/// - AI Chat Input for adjustments
/// - View on Map button
/// - Manual Save for preview mode
class ItineraryDetailScreen extends StatefulWidget {
  final Itinerary itinerary;
  final String? tripId;           // null = 未保存（预览模式）
  final List<String>? cities;     // 用于保存时传给后端
  final int? days;                // 用于保存时传给后端
  final List<String>? interests;  // 用于保存时传给后端

  const ItineraryDetailScreen({
    super.key,
    required this.itinerary,
    this.tripId,
    this.cities,
    this.days,
    this.interests,
  });

  @override
  State<ItineraryDetailScreen> createState() => _ItineraryDetailScreenState();
}

class _ItineraryDetailScreenState extends State<ItineraryDetailScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  bool _isSaved = false;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(
      length: widget.itinerary.days.length,
      vsync: this,
    );
    // 检查是否已保存：有 tripId 且不是 preview_ 开头
    _isSaved = widget.tripId != null && !widget.tripId!.startsWith('preview_');
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: _isSaved,
      onPopInvoked: (bool didPop) async {
        if (didPop) return;

        final discard = await showDialog<bool>(
          context: context,
          builder: (ctx) => AlertDialog(
            title: const Text('Discard itinerary?'),
            content: const Text('This trip has not been saved. Are you sure you want to leave?'),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx, false),
                child: const Text('Cancel'),
              ),
              TextButton(
                onPressed: () => Navigator.pop(ctx, true),
                child: const Text('Discard', style: TextStyle(color: Colors.red)),
              ),
            ],
          ),
        );

        if (discard == true && context.mounted) {
          Navigator.of(context).pop();
        }
      },
      child: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.gray900),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          '${widget.itinerary.destination} · ${widget.itinerary.totalDays} Days',
          style: AppTextStyles.h4(color: AppColors.gray900),
        ),
        actions: [
          if (!_isSaved)
            TextButton.icon(
              onPressed: (_isSaving || _isSaved) ? null : _saveTrip,
              icon: const Icon(Icons.bookmark_add, color: AppColors.jade500, size: 20),
              label: Text(
                _isSaving ? 'Saving...' : 'Save',
                style: const TextStyle(color: AppColors.jade500, fontWeight: FontWeight.w600),
              ),
            )
          else
            const Padding(
              padding: EdgeInsets.only(right: 12),
              child: Icon(Icons.bookmark, color: AppColors.jade500, size: 24),
            ),
          IconButton(
            icon: const Icon(Icons.share_outlined, color: AppColors.gray700),
            onPressed: _handleShare,
            tooltip: 'Share',
          ),
        ],
      ),
      body: Column(
        children: [
          // AI Generated Banner
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
            decoration: const BoxDecoration(
              color: AppColors.jade50,
              border: Border(
                bottom: BorderSide(color: AppColors.gray200, width: 1),
              ),
            ),
            child: const Center(
              child: Text(
                '✨ Generated by AI',
                style: TextStyle(color: AppColors.jade500, fontSize: 14),
              ),
            ),
          ),

          // Day Tab Bar
          Container(
            decoration: const BoxDecoration(
              color: Colors.white,
              border: Border(
                bottom: BorderSide(color: AppColors.gray200, width: 1),
              ),
            ),
            child: TabBar(
              controller: _tabController,
              isScrollable: widget.itinerary.days.length > 3,
              labelColor: AppColors.jade500,
              unselectedLabelColor: AppColors.gray600,
              labelStyle: AppTextStyles.body(color: AppColors.jade500).copyWith(
                fontWeight: FontWeight.w600,
              ),
              unselectedLabelStyle: AppTextStyles.body(color: AppColors.gray600),
              indicatorColor: AppColors.jade500,
              indicatorWeight: 2,
              tabs: widget.itinerary.days.map((day) {
                return Tab(text: 'Day ${day.dayNumber}');
              }).toList(),
            ),
          ),

          // Day Content (swipeable)
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: widget.itinerary.days.map((day) {
                return _buildDayContent(day);
              }).toList(),
            ),
          ),

          // AI Chat Input (fixed at bottom)
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              border: const Border(
                top: BorderSide(color: AppColors.gray200, width: 1),
              ),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 10,
                  offset: const Offset(0, -2),
                ),
              ],
            ),
            child: AiChatInput(
              onSend: (text) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('AI itinerary editing coming in next update')),
                );
              },
              placeholder: 'e.g. "add more food stops"',
            ),
          ),
        ],
      ),
      ),
    );
  }

  Widget _buildDayContent(ItineraryDay day) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Day Title
          if (day.title != null) ...[
            Text(
              '${day.title}',
              style: AppTextStyles.h3(color: AppColors.gray900),
            ),
            const SizedBox(height: 16),
          ],

          // Activities with Transit Connectors
          ...List.generate(day.activities.length, (index) {
            final activity = day.activities[index];
            final isLast = index == day.activities.length - 1;

            return Column(
              children: [
                ActivityCard(
                  activity: activity,
                  onNavigate: () => _handleNavigate(activity),
                  onDetails: () => _showActivityDetail(activity.toJson()),
                ),
                if (!isLast) _buildTransitConnector(activity, day.activities[index + 1]),
              ],
            );
          }),

          const SizedBox(height: 16),

          // Add Stop Button
          OutlinedButton.icon(
            onPressed: _handleAddStop,
            icon: const Icon(Icons.add, size: 18),
            label: const Text('Add Stop'),
            style: OutlinedButton.styleFrom(
              foregroundColor: AppColors.jade500,
              side: const BorderSide(color: AppColors.jade500),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            ),
          ),

          const SizedBox(height: 24),

          // View on Map Button
          SizedBox(
            width: double.infinity,
            height: 48,
            child: ElevatedButton(
              onPressed: _handleViewOnMap,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.jade500,
                foregroundColor: Colors.white,
                elevation: 0,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.map_outlined, size: 20),
                  SizedBox(width: 8),
                  Text(
                    'View on Map',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              ),
            ),
          ),

          const SizedBox(height: 16),
        ],
      ),
    );
  }

  Widget _buildTransitConnector(Activity from, Activity to) {
    // Calculate time difference between activities
    final durationMinutes = to.startTime.difference(from.endTime).inMinutes;

    // If no gap or invalid time difference, show simple separator
    if (durationMinutes <= 0) {
      return const Padding(
        padding: EdgeInsets.symmetric(vertical: 8),
        child: Center(child: Icon(Icons.more_vert, color: Colors.grey, size: 20)),
      );
    }

    // Show time gap between activities
    if (durationMinutes <= 15) {
      return TransitConnector(
        transitText: '$durationMinutes min gap',
        icon: Icons.access_time,
      );
    } else if (durationMinutes <= 60) {
      return TransitConnector(
        transitText: '$durationMinutes min gap',
        icon: Icons.access_time,
      );
    } else {
      final hours = (durationMinutes / 60).floor();
      final mins = durationMinutes % 60;
      final timeText = mins > 0 ? '${hours}h ${mins}m gap' : '${hours}h gap';
      return TransitConnector(
        transitText: timeText,
        icon: Icons.schedule,
      );
    }
  }

  void _handleNavigate(Activity activity) {
    final nameZh = activity.notes ?? activity.location ?? '';
    final nameEn = activity.title;
    debugPrint('🧭 Navigate tapped: nameZh=$nameZh, nameEn=$nameEn, city=${widget.itinerary.destination}');
    // 搜索用中文（精确匹配），搜索框显示英文（用户可读）
    final searchQuery = nameZh.isNotEmpty ? nameZh : nameEn;
    final displayName = nameEn.isNotEmpty ? nameEn : nameZh;

    // 返回 MainScreen 并切换到 Map tab + 自动搜索
    Navigator.of(context).popUntil((route) => route.isFirst);
    MainScreen.globalKey.currentState?.switchToMapAndSearch(
      searchQuery,
      displayName: displayName,
      city: widget.itinerary.destination,
    );
  }

  Future<void> _showActivityDetail(Map<String, dynamic> activity) async {
    final nameZh = activity['name_zh'] ?? activity['notes'] ?? activity['location'] ?? '';
    final nameEn = activity['name'] ?? activity['title'] ?? '';

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => ActivityDetailSheet(
        nameEn: nameEn,
        nameZh: nameZh,
        description: activity['description'] ?? '',
        duration: activity['duration'] ?? '',
        cost: activity['cost'] ?? '',
        city: widget.itinerary.destination,
      ),
    );
  }

  Future<void> _saveTrip() async {
    if (_isSaved || _isSaving) return;  // 防重复点击
    debugPrint('💾 Saving trip, user_id: ${AuthService.currentUserId}');
    debugPrint('💾 Itinerary days: ${widget.itinerary.toJson()['days']?.map((d) => d['day_number'])}');
    setState(() => _isSaving = true);
    try {
      await ApiClient.post(BackendConfig.tripUrl, {
        'action': 'create',
        'cities': widget.cities ?? [widget.itinerary.destination],
        'days': widget.itinerary.days.length,  // 用实际天数，不依赖 widget.days
        'interests': widget.interests ?? [],
        'title': widget.itinerary.title,
        'itinerary': widget.itinerary.toJson(),
        'user_id': AuthService.currentUserId,
      });

      if (mounted) {
        setState(() {
          _isSaved = true;
          _isSaving = false;
        });
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Trip saved to My Trips!')),
        );
      }
    } catch (e) {
      debugPrint('❌ Save trip error: $e');
      if (mounted) {
        setState(() => _isSaving = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Save failed: $e')),
        );
      }
    }
  }

  void _handleShare() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Share functionality coming soon')),
    );
    // TODO: Implement share functionality
  }

  void _handleAddStop() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Add stop functionality coming soon')),
    );
    // TODO: Add stop functionality
  }

  void _handleViewOnMap() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('View on map functionality coming soon')),
    );
    // TODO: Navigate to Map tab with all itinerary points
  }
}

/// POI Details Bottom Sheet with Photos
class _POIDetailsSheet extends StatefulWidget {
  final Activity activity;

  const _POIDetailsSheet({required this.activity});

  @override
  State<_POIDetailsSheet> createState() => _POIDetailsSheetState();
}

class _POIDetailsSheetState extends State<_POIDetailsSheet> {
  bool _isLoading = true;
  List<Map<String, dynamic>> _photos = [];
  String? _errorMessage;
  int _currentPhotoIndex = 0;

  @override
  void initState() {
    super.initState();
    _fetchPhotos();
  }

  Future<void> _fetchPhotos() async {
    try {
      // Use Chinese name for photo search (Activity doesn't have poiId field)
      final nameZh = widget.activity.notes ?? widget.activity.location ?? widget.activity.title;

      final result = await ApiClient.post(
        BackendConfig.poiPhotoUrl,
        {
          'name_zh': nameZh,
          'limit': 5,
        },
        timeout: const Duration(seconds: 15),
      );

      if (mounted) {
        final photos = (result['photos'] as List?)?.cast<Map<String, dynamic>>() ?? [];
        setState(() {
          _photos = photos;
          _isLoading = false;
        });
      }
    } catch (e) {
      debugPrint('❌ Fetch POI photos failed: $e');
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Failed to load photos';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.7,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      expand: false,
      builder: (context, scrollController) => Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
        ),
        child: Column(
          children: [
            // Drag Handle
            Container(
              margin: const EdgeInsets.only(top: 12, bottom: 8),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(2),
              ),
            ),

            Expanded(
              child: SingleChildScrollView(
                controller: scrollController,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Photos Carousel
                    if (_isLoading)
                      Container(
                        height: 250,
                        color: Colors.grey[200],
                        child: const Center(
                          child: CircularProgressIndicator(color: AppColors.jade500),
                        ),
                      )
                    else if (_photos.isNotEmpty)
                      _buildPhotoCarousel()
                    else
                      Container(
                        height: 200,
                        color: Colors.grey[100],
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.image_not_supported, size: 48, color: Colors.grey[400]),
                              const SizedBox(height: 8),
                              Text(
                                _errorMessage ?? 'No photos available',
                                style: TextStyle(color: Colors.grey[600]),
                              ),
                            ],
                          ),
                        ),
                      ),

                    // Content Padding
                    Padding(
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // Title
                          Text(
                            widget.activity.title,
                            style: AppTextStyles.h3(color: AppColors.gray900),
                          ),
                          const SizedBox(height: 12),

                          // Time
                          Row(
                            children: [
                              const Icon(Icons.access_time, size: 16, color: AppColors.gray600),
                              const SizedBox(width: 6),
                              Text(
                                '${_formatTime(widget.activity.startTime)} - ${_formatTime(widget.activity.endTime)}',
                                style: AppTextStyles.bodySmall(color: AppColors.gray600),
                              ),
                            ],
                          ),

                          // Description
                          if (widget.activity.description != null) ...[
                            const SizedBox(height: 16),
                            Text(
                              widget.activity.description!,
                              style: AppTextStyles.body(color: AppColors.gray700),
                            ),
                          ],

                          // Address
                          if (widget.activity.address != null) ...[
                            const SizedBox(height: 16),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Icon(Icons.location_on, size: 18, color: AppColors.jade500),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    widget.activity.address!,
                                    style: AppTextStyles.body(color: AppColors.gray600),
                                  ),
                                ),
                              ],
                            ),
                          ],

                          // Notes (Chinese name)
                          if (widget.activity.notes != null) ...[
                            const SizedBox(height: 12),
                            Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                                color: AppColors.jade50,
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Row(
                                children: [
                                  const Icon(Icons.translate, size: 16, color: AppColors.jade500),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: Text(
                                      widget.activity.notes!,
                                      style: AppTextStyles.bodySmall(color: AppColors.gray700),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPhotoCarousel() {
    return Column(
      children: [
        SizedBox(
          height: 250,
          child: PageView.builder(
            itemCount: _photos.length,
            onPageChanged: (index) {
              setState(() => _currentPhotoIndex = index);
            },
            itemBuilder: (context, index) {
              final photo = _photos[index];
              final url = photo['url'] as String?;

              return GestureDetector(
                onTap: () {
                  // Full screen photo view
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (_) => _FullScreenPhotoView(
                        photos: _photos,
                        initialIndex: index,
                      ),
                    ),
                  );
                },
                child: Image.network(
                  url ?? '',
                  fit: BoxFit.cover,
                  loadingBuilder: (context, child, loadingProgress) {
                    if (loadingProgress == null) return child;
                    return Container(
                      color: Colors.grey[200],
                      child: Center(
                        child: CircularProgressIndicator(
                          value: loadingProgress.expectedTotalBytes != null
                              ? loadingProgress.cumulativeBytesLoaded /
                                  loadingProgress.expectedTotalBytes!
                              : null,
                          color: AppColors.jade500,
                        ),
                      ),
                    );
                  },
                  errorBuilder: (context, error, stackTrace) {
                    return Container(
                      color: Colors.grey[200],
                      child: const Center(
                        child: Icon(Icons.broken_image, size: 48, color: Colors.grey),
                      ),
                    );
                  },
                ),
              );
            },
          ),
        ),

        // Photo Counter & Caption
        if (_photos.isNotEmpty)
          Container(
            padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
            color: Colors.black.withOpacity(0.6),
            child: Row(
              children: [
                // Counter
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.5),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${_currentPhotoIndex + 1}/${_photos.length}',
                    style: const TextStyle(color: Colors.white, fontSize: 12),
                  ),
                ),
                const SizedBox(width: 12),

                // Caption
                Expanded(
                  child: Text(
                    _photos[_currentPhotoIndex]['caption'] as String? ?? '',
                    style: const TextStyle(color: Colors.white, fontSize: 13),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }

  String _formatTime(DateTime time) {
    final hour = time.hour.toString().padLeft(2, '0');
    final minute = time.minute.toString().padLeft(2, '0');
    return '$hour:$minute';
  }
}

/// Full Screen Photo Viewer
class _FullScreenPhotoView extends StatefulWidget {
  final List<Map<String, dynamic>> photos;
  final int initialIndex;

  const _FullScreenPhotoView({
    required this.photos,
    required this.initialIndex,
  });

  @override
  State<_FullScreenPhotoView> createState() => _FullScreenPhotoViewState();
}

class _FullScreenPhotoViewState extends State<_FullScreenPhotoView> {
  late PageController _controller;
  late int _currentIndex;

  @override
  void initState() {
    super.initState();
    _currentIndex = widget.initialIndex;
    _controller = PageController(initialPage: widget.initialIndex);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          '${_currentIndex + 1}/${widget.photos.length}',
          style: const TextStyle(color: Colors.white),
        ),
      ),
      body: Stack(
        children: [
          PageView.builder(
            controller: _controller,
            itemCount: widget.photos.length,
            onPageChanged: (index) {
              setState(() => _currentIndex = index);
            },
            itemBuilder: (context, index) {
              final photo = widget.photos[index];
              return InteractiveViewer(
                child: Center(
                  child: Image.network(
                    photo['url'] as String,
                    fit: BoxFit.contain,
                    errorBuilder: (context, error, stackTrace) {
                      return const Center(
                        child: Icon(Icons.broken_image, size: 64, color: Colors.grey),
                      );
                    },
                  ),
                ),
              );
            },
          ),

          // Caption at bottom
          if (widget.photos[_currentIndex]['caption'] != null)
            Positioned(
              bottom: 0,
              left: 0,
              right: 0,
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [
                      Colors.transparent,
                      Colors.black.withOpacity(0.7),
                    ],
                  ),
                ),
                child: Text(
                  widget.photos[_currentIndex]['caption'] as String,
                  style: const TextStyle(color: Colors.white, fontSize: 14),
                  textAlign: TextAlign.center,
                ),
              ),
            ),
        ],
      ),
    );
  }
}
/// Activity Detail Sheet Widget
class _ActivityDetailSheet extends StatefulWidget {
  final String nameEn;
  final String nameZh;
  final String description;
  final String duration;
  final String cost;
  final String city;

  const _ActivityDetailSheet({
    required this.nameEn,
    required this.nameZh,
    required this.description,
    required this.duration,
    required this.cost,
    required this.city,
  });

  @override
  State<_ActivityDetailSheet> createState() => _ActivityDetailSheetState();
}

class _ActivityDetailSheetState extends State<_ActivityDetailSheet> {
  bool _isLoading = true;
  List<Map<String, dynamic>> _photos = [];
  String? _errorMessage;
  int _currentPhotoIndex = 0;

  @override
  void initState() {
    super.initState();
    _fetchPhotos();
  }

  Future<void> _fetchPhotos() async {
    try {
      final result = await ApiClient.post(
        ApiClient.poiPhotoUrl,
        {
          'name_zh': widget.nameZh,
          'city': widget.city,
          'limit': 5,
        },
        timeout: const Duration(seconds: 15),
      );

      if (mounted) {
        final photos = (result['photos'] as List?)?.cast<Map<String, dynamic>>() ?? [];
        setState(() {
          _photos = photos;
          _isLoading = false;
        });
      }
    } catch (e) {
      debugPrint('❌ Fetch POI photos failed: $e');
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Failed to load photos';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.75,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      expand: false,
      builder: (context, scrollController) => Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
        ),
        child: Column(
          children: [
            // Drag Handle
            Container(
              margin: const EdgeInsets.only(top: 12, bottom: 8),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(2),
              ),
            ),

            Expanded(
              child: SingleChildScrollView(
                controller: scrollController,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Photos Carousel
                    if (_isLoading)
                      Container(
                        height: 250,
                        color: Colors.grey[200],
                        child: const Center(
                          child: CircularProgressIndicator(color: AppColors.jade500),
                        ),
                      )
                    else if (_photos.isNotEmpty)
                      _buildPhotoCarousel()
                    else
                      Container(
                        height: 200,
                        color: Colors.grey[100],
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.image_not_supported, size: 48, color: Colors.grey[400]),
                              const SizedBox(height: 8),
                              Text(
                                _errorMessage ?? 'No photos available',
                                style: TextStyle(color: Colors.grey[600]),
                              ),
                            ],
                          ),
                        ),
                      ),

                    // Content
                    Padding(
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // English Name
                          Text(
                            widget.nameEn,
                            style: AppTextStyles.h3(color: AppColors.gray900),
                          ),

                          // Chinese Name
                          if (widget.nameZh.isNotEmpty) ...[
                            const SizedBox(height: 8),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                              decoration: BoxDecoration(
                                color: AppColors.jade50,
                                borderRadius: BorderRadius.circular(6),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  const Icon(Icons.translate, size: 14, color: AppColors.jade500),
                                  const SizedBox(width: 6),
                                  Text(
                                    widget.nameZh,
                                    style: AppTextStyles.bodySmall(color: AppColors.gray700),
                                  ),
                                ],
                              ),
                            ),
                          ],

                          const SizedBox(height: 16),

                          // Duration
                          if (widget.duration.isNotEmpty) ...[
                            Row(
                              children: [
                                const Icon(Icons.access_time, size: 16, color: AppColors.gray600),
                                const SizedBox(width: 6),
                                Text(
                                  widget.duration,
                                  style: AppTextStyles.bodySmall(color: AppColors.gray600),
                                ),
                              ],
                            ),
                            const SizedBox(height: 12),
                          ],

                          // Cost
                          if (widget.cost.isNotEmpty) ...[
                            Row(
                              children: [
                                const Icon(Icons.attach_money, size: 16, color: AppColors.gray600),
                                const SizedBox(width: 6),
                                Text(
                                  widget.cost,
                                  style: AppTextStyles.bodySmall(color: AppColors.gray600),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                          ],

                          // Description
                          if (widget.description.isNotEmpty) ...[
                            Text(
                              widget.description,
                              style: AppTextStyles.body(color: AppColors.gray700),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPhotoCarousel() {
    return Column(
      children: [
        SizedBox(
          height: 250,
          child: PageView.builder(
            itemCount: _photos.length,
            onPageChanged: (index) {
              setState(() => _currentPhotoIndex = index);
            },
            itemBuilder: (context, index) {
              final photo = _photos[index];
              final url = photo['url'] as String?;

              return GestureDetector(
                onTap: () {
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (_) => _FullScreenPhotoView(
                        photos: _photos,
                        initialIndex: index,
                      ),
                    ),
                  );
                },
                child: Image.network(
                  url ?? '',
                  fit: BoxFit.cover,
                  loadingBuilder: (context, child, loadingProgress) {
                    if (loadingProgress == null) return child;
                    return Container(
                      color: Colors.grey[200],
                      child: Center(
                        child: CircularProgressIndicator(
                          value: loadingProgress.expectedTotalBytes != null
                              ? loadingProgress.cumulativeBytesLoaded /
                                  loadingProgress.expectedTotalBytes!
                              : null,
                          color: AppColors.jade500,
                        ),
                      ),
                    );
                  },
                  errorBuilder: (context, error, stackTrace) {
                    return Container(
                      color: Colors.grey[200],
                      child: const Center(
                        child: Icon(Icons.broken_image, size: 48, color: Colors.grey),
                      ),
                    );
                  },
                ),
              );
            },
          ),
        ),

        // Photo Counter & Caption
        if (_photos.isNotEmpty)
          Container(
            padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
            color: Colors.black.withOpacity(0.6),
            child: Row(
              children: [
                // Counter
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.5),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${_currentPhotoIndex + 1}/${_photos.length}',
                    style: const TextStyle(color: Colors.white, fontSize: 12),
                  ),
                ),
                const SizedBox(width: 12),

                // Caption
                Expanded(
                  child: Text(
                    _photos[_currentPhotoIndex]['caption'] as String? ?? '',
                    style: const TextStyle(color: Colors.white, fontSize: 13),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}
